//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeRiserAPI.QueryPushService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventDataType", Namespace="http://schemas.datacontract.org/2004/07/QueryService")]
    [System.SerializableAttribute()]
    public partial class EventDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.AnswerPackage EventMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.AnswerPackage EventMessage {
            get {
                return this.EventMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.EventMessageField, value) != true)) {
                    this.EventMessageField = value;
                    this.RaisePropertyChanged("EventMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerPackage", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class AnswerPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.PresentationPackage[] PresentationTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.ComputedResultTable ProcessedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.RawDataResultTable[] RawDataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] ResultSymbolsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserQuerySessionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.PresentationPackage[] PresentationTypes {
            get {
                return this.PresentationTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationTypesField, value) != true)) {
                    this.PresentationTypesField = value;
                    this.RaisePropertyChanged("PresentationTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.ComputedResultTable ProcessedResults {
            get {
                return this.ProcessedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessedResultsField, value) != true)) {
                    this.ProcessedResultsField = value;
                    this.RaisePropertyChanged("ProcessedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryID {
            get {
                return this.QueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryIDField, value) != true)) {
                    this.QueryIDField = value;
                    this.RaisePropertyChanged("QueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.RawDataResultTable[] RawDataResults {
            get {
                return this.RawDataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataResultsField, value) != true)) {
                    this.RawDataResultsField = value;
                    this.RaisePropertyChanged("RawDataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] ResultSymbols {
            get {
                return this.ResultSymbolsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSymbolsField, value) != true)) {
                    this.ResultSymbolsField = value;
                    this.RaisePropertyChanged("ResultSymbols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserQuerySessionID {
            get {
                return this.UserQuerySessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserQuerySessionIDField, value) != true)) {
                    this.UserQuerySessionIDField = value;
                    this.RaisePropertyChanged("UserQuerySessionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComputedResultTable", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class ComputedResultTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] ComputedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenericField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeaderDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] KeyFieldIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] ComputedResults {
            get {
                return this.ComputedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputedResultsField, value) != true)) {
                    this.ComputedResultsField = value;
                    this.RaisePropertyChanged("ComputedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Generic {
            get {
                return this.GenericField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericField, value) != true)) {
                    this.GenericField = value;
                    this.RaisePropertyChanged("Generic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] HeaderDataType {
            get {
                return this.HeaderDataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderDataTypeField, value) != true)) {
                    this.HeaderDataTypeField = value;
                    this.RaisePropertyChanged("HeaderDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] KeyFieldIndex {
            get {
                return this.KeyFieldIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyFieldIndexField, value) != true)) {
                    this.KeyFieldIndexField = value;
                    this.RaisePropertyChanged("KeyFieldIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PresentationPackage", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class PresentationPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainWidgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainWidgetAltNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubWidgetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubWidgetsAltNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainWidget {
            get {
                return this.MainWidgetField;
            }
            set {
                if ((object.ReferenceEquals(this.MainWidgetField, value) != true)) {
                    this.MainWidgetField = value;
                    this.RaisePropertyChanged("MainWidget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainWidgetAltName {
            get {
                return this.MainWidgetAltNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MainWidgetAltNameField, value) != true)) {
                    this.MainWidgetAltNameField = value;
                    this.RaisePropertyChanged("MainWidgetAltName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubWidgets {
            get {
                return this.SubWidgetsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWidgetsField, value) != true)) {
                    this.SubWidgetsField = value;
                    this.RaisePropertyChanged("SubWidgets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubWidgetsAltName {
            get {
                return this.SubWidgetsAltNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWidgetsAltNameField, value) != true)) {
                    this.SubWidgetsAltNameField = value;
                    this.RaisePropertyChanged("SubWidgetsAltName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RawDataResultTable", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class RawDataResultTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.ChartDataPairing[] ChartReadyDataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][][] DataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTimeFrameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] HeaderDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.HighlightRegion[] HighLightRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TradeRiserAPI.QueryPushService.PerformanceStats[] PerformanceStatisticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SummariesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.ChartDataPairing[] ChartReadyDataResults {
            get {
                return this.ChartReadyDataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartReadyDataResultsField, value) != true)) {
                    this.ChartReadyDataResultsField = value;
                    this.RaisePropertyChanged("ChartReadyDataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][][] DataResults {
            get {
                return this.DataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataResultsField, value) != true)) {
                    this.DataResultsField = value;
                    this.RaisePropertyChanged("DataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTimeFrame {
            get {
                return this.DataTimeFrameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTimeFrameField, value) != true)) {
                    this.DataTimeFrameField = value;
                    this.RaisePropertyChanged("DataTimeFrame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] HeaderDataType {
            get {
                return this.HeaderDataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderDataTypeField, value) != true)) {
                    this.HeaderDataTypeField = value;
                    this.RaisePropertyChanged("HeaderDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.HighlightRegion[] HighLightRegion {
            get {
                return this.HighLightRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.HighLightRegionField, value) != true)) {
                    this.HighLightRegionField = value;
                    this.RaisePropertyChanged("HighLightRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TradeRiserAPI.QueryPushService.PerformanceStats[] PerformanceStatistics {
            get {
                return this.PerformanceStatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceStatisticsField, value) != true)) {
                    this.PerformanceStatisticsField = value;
                    this.RaisePropertyChanged("PerformanceStatistics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Summaries {
            get {
                return this.SummariesField;
            }
            set {
                if ((object.ReferenceEquals(this.SummariesField, value) != true)) {
                    this.SummariesField = value;
                    this.RaisePropertyChanged("Summaries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChartDataPairing", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class ChartDataPairing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ColumnHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] GenericStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumericTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RowHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XaxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YaxisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ColumnHeaders {
            get {
                return this.ColumnHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnHeadersField, value) != true)) {
                    this.ColumnHeadersField = value;
                    this.RaisePropertyChanged("ColumnHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] GenericStr {
            get {
                return this.GenericStrField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericStrField, value) != true)) {
                    this.GenericStrField = value;
                    this.RaisePropertyChanged("GenericStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumericType {
            get {
                return this.NumericTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumericTypeField, value) != true)) {
                    this.NumericTypeField = value;
                    this.RaisePropertyChanged("NumericType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RowHeaders {
            get {
                return this.RowHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.RowHeadersField, value) != true)) {
                    this.RowHeadersField = value;
                    this.RaisePropertyChanged("RowHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xaxis {
            get {
                return this.XaxisField;
            }
            set {
                if ((object.ReferenceEquals(this.XaxisField, value) != true)) {
                    this.XaxisField = value;
                    this.RaisePropertyChanged("Xaxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yaxis {
            get {
                return this.YaxisField;
            }
            set {
                if ((object.ReferenceEquals(this.YaxisField, value) != true)) {
                    this.YaxisField = value;
                    this.RaisePropertyChanged("Yaxis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HighlightRegion", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class HighlightRegion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AxisIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeriesIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AxisIndex {
            get {
                return this.AxisIndexField;
            }
            set {
                if ((this.AxisIndexField.Equals(value) != true)) {
                    this.AxisIndexField = value;
                    this.RaisePropertyChanged("AxisIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeriesIndex {
            get {
                return this.SeriesIndexField;
            }
            set {
                if ((this.SeriesIndexField.Equals(value) != true)) {
                    this.SeriesIndexField = value;
                    this.RaisePropertyChanged("SeriesIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceStats", Namespace="http://schemas.datacontract.org/2004/07/QueryLibrary")]
    [System.SerializableAttribute()]
    public partial class PerformanceStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerformanceStatsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] StatsLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PerformanceStatsType {
            get {
                return this.PerformanceStatsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceStatsTypeField, value) != true)) {
                    this.PerformanceStatsTypeField = value;
                    this.RaisePropertyChanged("PerformanceStatsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] StatsLog {
            get {
                return this.StatsLogField;
            }
            set {
                if ((object.ReferenceEquals(this.StatsLogField, value) != true)) {
                    this.StatsLogField = value;
                    this.RaisePropertyChanged("StatsLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueryPushService.IQueryPushService", CallbackContract=typeof(TradeRiserAPI.QueryPushService.IQueryPushServiceCallback))]
    public interface IQueryPushService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IQueryPushService/RegisterClient")]
        void RegisterClient(string clientName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IQueryPushService/NotifyServer")]
        void NotifyServer(TradeRiserAPI.QueryPushService.EventDataType eventData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryPushServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IQueryPushService/BroadcastToClient")]
        void BroadcastToClient(TradeRiserAPI.QueryPushService.EventDataType eventData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryPushServiceChannel : TradeRiserAPI.QueryPushService.IQueryPushService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryPushServiceClient : System.ServiceModel.DuplexClientBase<TradeRiserAPI.QueryPushService.IQueryPushService>, TradeRiserAPI.QueryPushService.IQueryPushService {
        
        public QueryPushServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public QueryPushServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public QueryPushServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPushServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPushServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterClient(string clientName) {
            base.Channel.RegisterClient(clientName);
        }
        
        public void NotifyServer(TradeRiserAPI.QueryPushService.EventDataType eventData) {
            base.Channel.NotifyServer(eventData);
        }
    }
}
